1. What is the difference bw touples and list 

List in python are used to store set of data in a squence. in list we can store string float and integer and float values. in list once the data are assigned they can be chnaged durig runtime. simply list are mutable data set.

tuples are same as list but they are immutable. it means once the data inside touples are defined they cannt be changed and touples are used when you want the values to be static.

Write a python program to find the maximum of three nums.


In [3]:
a = int(input("enter value"))
b = int(input("enter value"))
c = int(input("enter value"))

if a > b & a > c:
    print("a is greater")
elif b > c & b> a:
    print("b is greater")
else:
    print( "c is greater")
    

enter value 8
enter value 6
enter value 77


c is greater


In [ ]:
What is funtion in python? Wap to return the  sq of a number 

In [7]:
def function():
    a = int(input("Enter a value to find sq"))
    square = a*a 
    print(square)

function()    
   

Enter a value to find sq 55


3025


Create a numpy array of first 10 multiples of 5 and multipy each no by 2 

In [10]:
import numpy as np

arr = np.arange(11)

In [11]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
arr1=arr[0:5]

In [19]:
arr2 = arr1 * 5

In [20]:
arr2

array([ 0,  5, 10, 15, 20])

In [21]:
arr2 / 2

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

Write the code to create a 3x3 num pay array filled with zeros.


In [30]:
import numpy as np 
arr3x3 = np.array([[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]])

In [24]:
arr3x3

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

How do you find the mean and stndard deviation of a numpy array 

In [32]:
import numpy as np

In [33]:
arr.mean()

np.float64(5.0)

In [34]:
arr.std()

np.float64(3.1622776601683795)

In [35]:
arrx = np.array([10,20,30,40,50])

In [36]:
arry = arrx[0:3]

In [37]:
arry

array([10, 20, 30])

In [45]:
zeros = np.zeros((3,3))

In [46]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [47]:
import pandas as pd 

In [49]:
df = pd.read_csv("student_scores.csv")

In [50]:
df

StudentID     Name  Subject  Marks  Age Grade
0          1    Alice     Math     85   20     B
1          2      Bob  Science     78   21     C
2          3  Charlie     Math     92   19     A
3          4    David  Science     68   22     D
4          5      Eva     Math     74   20     C
5          6    Frank  Science     88   23     B

In [51]:
df.head(3)

StudentID     Name  Subject  Marks  Age Grade
0          1    Alice     Math     85   20     B
1          2      Bob  Science     78   21     C
2          3  Charlie     Math     92   19     A

In [53]:
marks = df["Marks"]

In [54]:
marks.mean()

np.float64(80.83333333333333)

In [65]:
marks2 = df[df['Marks']>=80]

In [66]:
marks2

StudentID     Name  Subject  Marks  Age Grade
0          1    Alice     Math     85   20     B
2          3  Charlie     Math     92   19     A
5          6    Frank  Science     88   23     B

In [57]:
subject = df['Subject']

In [58]:
subject

0       Math
1    Science
2       Math
3    Science
4       Math
5    Science
Name: Subject, dtype: object

In [94]:
df['Pass/fail ']='fail'
df.loc[df['Marks']>=75,'Pass/fail'] = 'Pass'
df

StudentID     Name  Subject  Marks  Age Grade  Pass1/Fail1  Pass1/Fail  \
0          1    Alice     Math     85   20     B            2           2   
1          2      Bob  Science     78   21     C            2           2   
2          3  Charlie     Math     92   19     A            3           3   
3          4    David  Science     68   22     D            4           4   
4          5      Eva     Math     74   20     C            6           6   
5          6    Frank  Science     88   23     B            5           5   

   Pass/Fail Pass/fail  Pass/fail  
0          2       fail      Pass  
1          2       fail      Pass  
2          3       fail      Pass  
3          4       fail       NaN  
4          6       fail       NaN  
5          5       fail      Pass

In [97]:
df.drop("Pass/Fail" ,axis= 1 ,inplace = True)

In [98]:
df.drop("Pass1/Fail" ,axis= 1,inplace = True)

In [83]:
asc = marks.sort_values(ascending = False)

In [103]:
df

StudentID     Name  Subject  Marks  Age Grade Pass/fail  Pass/fail
0          1    Alice     Math     85   20     B       fail      Pass
1          2      Bob  Science     78   21     C       fail      Pass
2          3  Charlie     Math     92   19     A       fail      Pass
3          4    David  Science     68   22     D       fail       NaN
4          5      Eva     Math     74   20     C       fail       NaN
5          6    Frank  Science     88   23     B       fail      Pass