In [4]:
import numpy as np
arr1 = np.array([0,50,5,40,77,60])
arr2 = np.array([0,40])

In [5]:
print(np.isin(arr1,arr2))

[ True False False  True False False]


In [6]:
print(np.isin(arr2,arr1))

[ True  True]


In [7]:
arrx = np.array([10,10,20,20,30,30])
print(str(np.unique(arrx)))

[10 20 30]


In [38]:
arry = np.array([[5,1],[7,4]])

In [39]:
arry

array([[5, 1],
       [7, 4]])

In [40]:
sorted_ar = np.sort(arry, axis = 0)

In [41]:
sorted_ar

array([[5, 1],
       [7, 4]])

In [42]:
sorted_ar2 = np.sort(arry, axis = 1)
sorted_ar2

array([[1, 5],
       [4, 7]])

In [43]:
arr4 = np.array([200,300,np.nan ,np.nan , np.nan ,700])
arr4

array([200., 300.,  nan,  nan,  nan, 700.])

In [44]:
arr5 = arr4[~np.isnan(arr4)]

In [45]:
arr5

array([200., 300., 700.])

In [74]:
arr6 = np.array([0,2,5,2,0,0,0,0,4,5,6,8,5,2,0,2,2])
arr7 = np.where(arr6 == 0 )[]

In [76]:
arr7

(array([ 0,  4,  5,  6,  7, 14]),)

In [78]:
arr8 = np.array([4584,87854,78745,54588,46547])
arr8

array([ 4584, 87854, 78745, 54588, 46547])

In [79]:
arr9 = np.argsort(arr8)

In [80]:
arr9

array([0, 4, 3, 2, 1])

In [93]:
arr3x3 = np.array([[1,2,3],[4,5,6],[6,7,8]])
arr3x3T = arr3x3.T
arr3x3T

array([[1, 4, 6],
       [2, 5, 7],
       [3, 6, 8]])

In [91]:
arr77 = np.array([5,8,7,8,9,7,8,7,8,9])
arr77[1:9]

array([8, 7, 8, 9, 7, 8, 7, 8])

In [94]:
arr3x3T

array([[1, 4, 6],
       [2, 5, 7],
       [3, 6, 8]])

In [97]:
arrd = np.diagonal(arr3x3T)

In [98]:
arrd

array([1, 5, 8])