In [4]:
import numpy as np 

arr2d = np.arange(10,51)

In [6]:
arr2d

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [97]:
arr3x3 = np.random.randint(1,100,(3,3))

In [98]:
arr3x3

array([[22, 60, 75],
       [95, 80, 93],
       [33, 84, 37]], dtype=int32)

In [100]:
zer = np.zeros(10)
zer

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [26]:
arr2d2 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])                           
arr2d2.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [28]:
arr2d2[0:4]

array([1, 2, 3, 4])

In [31]:
arr2d2[4:8]

array([5, 6, 7, 8])

In [37]:
print( arr2d2[2],arr2d2[6],arr2d2[10])

3 7 11


In [38]:
print( arr2d2[3],arr2d2[7],arr2d2[11])

4 8 12


In [84]:
arrx = np.array([[1,2,3],[1,2,3]])

arrz = np.vstack(arrx)
arrz




array([1, 2, 3, 1, 2, 3])

In [85]:
arrh = np.hstack(arrx)
arrh

array([1, 2, 3, 1, 2, 3])

In [78]:
arrx1 = np.array([40,55,401,12,78,11,26])


In [195]:
sarrx1 = np.sort(arrx1 )
sarrx1

array([ 11,  12,  26,  40,  55,  78, 401])

In [112]:
arrx2 = arrx1[arrx1>=50]
arrx2

array([ 55, 401,  78])

In [114]:
arreven = arrx1[arrx1%2==0]
arreven

array([40, 12, 78, 26])

In [110]:
arro = np.array([0,1,7,3,4,5])
arro
sarro = np.sort(arro )
sarro

array([0, 1, 3, 4, 5, 7])

In [71]:
orignal = np.array([5,5,5,5,5,5])
orignal

array([5, 5, 5, 5, 5, 5])

In [72]:
modified = orignal+ np.array([6,6,6,6,6,6])

In [73]:
modified

array([11, 11, 11, 11, 11, 11])

In [74]:
orignal

array([5, 5, 5, 5, 5, 5])

In [115]:
arrf = np.array([[1,2,3],[4,5,6]])

In [116]:
arrf

array([[1, 2, 3],
       [4, 5, 6]])

In [132]:
for row in arrf:
    for ele in row:
        print(ele)

1
2
3
4
5
6


In [192]:
arr4x4 = np.random.randint(1,2,(4,4))

In [186]:
arr4x4

array([[0, 1, 1, 0],
       [1, 1, 0, 1],
       [1, 1, 1, 1],
       [0, 1, 1, 0]], dtype=int32)

In [137]:
arrf.mean()

np.float64(3.5)

In [138]:
arrf.std()

np.float64(1.707825127659933)

In [196]:
arrf.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [200]:
arr12 = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16])
arrshape =arr12.reshape(4,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [151]:
arrshape

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [167]:
xxr=arrshape.view()

In [169]:
xxr + 5

array([[ 6,  7,  8,  9],
       [10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [170]:
arrshape

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [179]:
s = np.random.permutation(arrshape)

In [180]:
s

array([[13, 14, 15, 16],
       [ 1,  2,  3,  4],
       [ 9, 10, 11, 12],
       [ 5,  6,  7,  8]])

In [201]:
arr99 = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16])

In [203]:
arr999 = np.split(arr99 , 4)

In [204]:
arr999

[array([1, 2, 3, 4]),
 array([5, 6, 7, 8]),
 array([ 9, 10, 11, 12]),
 array([13, 14, 15, 16])]

In [208]:
arrj = np.array([1,5,9])
arrk = np.array([3,5,7])

np.concatenate([arrj ,arrk])

array([1, 5, 9, 3, 5, 7])

In [215]:
neg = np.array([1,-5,3,-3])

In [216]:
neg

array([ 1, -5,  3, -3])

In [224]:
np.random.normal(2, 3 , 1000)

array([ 9.98579475e+00,  3.02528714e+00,  5.34799492e+00,  2.98942879e+00,
        4.10594708e+00, -6.95291940e-01,  2.66462365e+00,  1.39685626e+00,
        4.25448851e-01,  3.25360638e+00, -1.55838917e+00,  1.47023339e+00,
        2.53955711e+00, -2.06651103e+00, -1.78333904e+00,  1.91659671e+00,
        3.88460498e+00,  1.01270640e+00,  1.64707783e+00,  3.68037033e+00,
        2.38542145e+00,  6.79703683e+00, -2.46223665e+00,  2.23467481e+00,
        5.58727121e+00,  3.00024011e+00,  7.82650027e+00,  6.80431110e+00,
        5.24729642e+00,  7.51122765e+00,  2.94679243e+00,  4.36991867e+00,
        4.06359370e-01, -1.12139693e+00,  9.03658543e-01, -3.25646633e+00,
        4.48516443e+00, -5.15236613e-01,  8.81904730e-01, -1.31952513e-01,
       -4.50737565e-01, -1.35145935e+00,  1.48898218e+00,  3.46377293e+00,
        5.48897941e+00,  2.23210826e+00,  1.34333732e+00,  1.52676992e+00,
       -3.91205779e-01,  3.77324252e+00,  3.63295932e-02, -1.38939746e-01,
        1.84556634e+00,  

In [226]:
np.random.binomial(n = 2 , p = 0.5 , size = 10)

array([1, 1, 0, 2, 1, 0, 1, 0, 0, 2], dtype=int32)

In [4]:
import pandas as pd

df = pd.read_csv("sample_employee_data.csv")

In [228]:
df

Name  Age  Gender Department Joining_Date  Salary  \
0    Employee_1   50  Female    Finance   01-01-2015   94505   
1    Employee_2   36    Male  Marketing   26-03-2015   82251   
2    Employee_3   29  Female         HR   18-06-2015   52662   
3    Employee_4   42    Male  Marketing   10-09-2015   38392   
4    Employee_5   40  Female         HR   04-12-2015   60535   
5    Employee_6   44    Male    Finance   26-02-2016   82256   
6    Employee_7   32  Female         IT   20-05-2016   65222   
7    Employee_8   32    Male         HR   12-08-2016   93335   
8    Employee_9   45    Male  Marketing   05-11-2016   40965   
9   Employee_10   57  Female    Finance   28-01-2017   54538   
10  Employee_11   45    Male         HR   22-04-2017   38110   
11  Employee_12   24  Female  Marketing   15-07-2017   57266   
12  Employee_13   43  Female  Marketing   08-10-2017   82992   
13  Employee_14   23  Female  Marketing   31-12-2017   36910   
14  Employee_15   45  Female         HR   25-03-2018   30206   
15  Employee_16   51  Female         HR   17-06-2018   53419   
16  Employee_17   59  Female         HR   10-09-2018   80636   
17  Employee_18   23  Female         IT   03-12-2018   80015   
18  Employee_19   42  Female         HR   25-02-2019   84268   
19  Employee_20   54  Female         HR   20-05-2019   48141   
20  Employee_21   33  Female         HR   13-08-2019   86044   
21  Employee_22   43  Female         IT   05-11-2019   97214   
22  Employee_23   46    Male         HR   28-01-2020   63827   
23  Employee_24   48    Male  Marketing   21-04-2020   85820   
24  Employee_25   49  Female         HR   15-07-2020   92623   
25  Employee_26   37  Female  Marketing   07-10-2020   52299   
26  Employee_27   36  Female  Marketing   30-12-2020   73585   
27  Employee_28   24  Female  Marketing   24-03-2021   94044   
28  Employee_29   58  Female         IT   17-06-2021   72557   
29  Employee_30   28  Female         IT   09-09-2021   79080   
30  Employee_31   42  Female         IT   02-12-2021   32693   
31  Employee_32   30  Female         HR   24-02-2022   99163   
32  Employee_33   39    Male  Marketing   20-05-2022   55939   
33  Employee_34   25  Female         IT   12-08-2022   78925   
34  Employee_35   46    Male         IT   04-11-2022   72941   
35  Employee_36   35  Female         HR   27-01-2023   51834   
36  Employee_37   30  Female         IT   22-04-2023   48047   
37  Employee_38   47    Male         HR   15-07-2023   56105   
38  Employee_39   23  Female    Finance   07-10-2023   45707   
39  Employee_40   41    Male         IT   31-12-2023   51976   

    Performance_Score  Attendance_Percentage  
0                2.27                  81.68  
1                1.44                  76.79  
2                1.91                  54.51  
3                2.71                  91.77  
4                4.27                  66.04  
5                4.44                  59.33  
6                1.03                  52.04  
7                3.04                  79.54  
8                2.67                  83.88  
9                1.89                  50.83  
10               1.48                  75.60  
11               2.35                  61.32  
12               4.77                  82.26  
13               2.29                  58.72  
14               3.08                  84.55  
15               3.81                  69.34  
16               2.45                  96.84  
17               4.89                  56.88  
18               4.85                  67.05  
19               2.01                  55.67  
20               2.99                  96.23  
21               2.20                  93.87  
22               2.14                  62.90  
23               1.15                  83.00  
24               3.44                  90.86  
25               3.01                  77.76  
26               1.21                  76.48  
27               2.11                  62.09  
28               4.63  

In [229]:
df.tail()

Name  Age  Gender Department Joining_Date  Salary  \
35  Employee_36   35  Female         HR   27-01-2023   51834   
36  Employee_37   30  Female         IT   22-04-2023   48047   
37  Employee_38   47    Male         HR   15-07-2023   56105   
38  Employee_39   23  Female    Finance   07-10-2023   45707   
39  Employee_40   41    Male         IT   31-12-2023   51976   

    Performance_Score  Attendance_Percentage  
35               4.05                  94.86  
36               1.95                  94.35  
37               3.91                  88.99  
38               2.47                  82.10  
39               3.53                  54.21

In [232]:
age = df['Age'] >= 25

In [233]:
age

0      True
1      True
2      True
3      True
4      True
5      True
6      True
7      True
8      True
9      True
10     True
11    False
12     True
13    False
14     True
15     True
16     True
17    False
18     True
19     True
20     True
21     True
22     True
23     True
24     True
25     True
26     True
27    False
28     True
29     True
30     True
31     True
32     True
33     True
34     True
35     True
36     True
37     True
38    False
39     True
Name: Age, dtype: bool

In [12]:
df['Bonus']=df['Salary'] * 10 / 100

In [13]:
df

Name  Age  Gender Department Joining_Date  Salary  \
0    Employee_1   50  Female    Finance   01-01-2015   94505   
1    Employee_2   36    Male  Marketing   26-03-2015   82251   
2    Employee_3   29  Female         HR   18-06-2015   52662   
3    Employee_4   42    Male  Marketing   10-09-2015   38392   
4    Employee_5   40  Female         HR   04-12-2015   60535   
5    Employee_6   44    Male    Finance   26-02-2016   82256   
6    Employee_7   32  Female         IT   20-05-2016   65222   
7    Employee_8   32    Male         HR   12-08-2016   93335   
8    Employee_9   45    Male  Marketing   05-11-2016   40965   
9   Employee_10   57  Female    Finance   28-01-2017   54538   
10  Employee_11   45    Male         HR   22-04-2017   38110   
11  Employee_12   24  Female  Marketing   15-07-2017   57266   
12  Employee_13   43  Female  Marketing   08-10-2017   82992   
13  Employee_14   23  Female  Marketing   31-12-2017   36910   
14  Employee_15   45  Female         HR   25-03-2018   30206   
15  Employee_16   51  Female         HR   17-06-2018   53419   
16  Employee_17   59  Female         HR   10-09-2018   80636   
17  Employee_18   23  Female         IT   03-12-2018   80015   
18  Employee_19   42  Female         HR   25-02-2019   84268   
19  Employee_20   54  Female         HR   20-05-2019   48141   
20  Employee_21   33  Female         HR   13-08-2019   86044   
21  Employee_22   43  Female         IT   05-11-2019   97214   
22  Employee_23   46    Male         HR   28-01-2020   63827   
23  Employee_24   48    Male  Marketing   21-04-2020   85820   
24  Employee_25   49  Female         HR   15-07-2020   92623   
25  Employee_26   37  Female  Marketing   07-10-2020   52299   
26  Employee_27   36  Female  Marketing   30-12-2020   73585   
27  Employee_28   24  Female  Marketing   24-03-2021   94044   
28  Employee_29   58  Female         IT   17-06-2021   72557   
29  Employee_30   28  Female         IT   09-09-2021   79080   
30  Employee_31   42  Female         IT   02-12-2021   32693   
31  Employee_32   30  Female         HR   24-02-2022   99163   
32  Employee_33   39    Male  Marketing   20-05-2022   55939   
33  Employee_34   25  Female         IT   12-08-2022   78925   
34  Employee_35   46    Male         IT   04-11-2022   72941   
35  Employee_36   35  Female         HR   27-01-2023   51834   
36  Employee_37   30  Female         IT   22-04-2023   48047   
37  Employee_38   47    Male         HR   15-07-2023   56105   
38  Employee_39   23  Female    Finance   07-10-2023   45707   
39  Employee_40   41    Male         IT   31-12-2023   51976   

    Performance_Score  Attendance_Percentage   Bonus  
0                2.27                  81.68  9450.5  
1                1.44                  76.79  8225.1  
2                1.91                  54.51  5266.2  
3                2.71                  91.77  3839.2  
4                4.27                  66.04  6053.5  
5                4.44                  59.33  8225.6  
6                1.03                  52.04  6522.2  
7                3.04                  79.54  9333.5  
8                2.67                  83.88  4096.5  
9                1.89                  50.83  5453.8  
10               1.48                  75.60  3811.0  
11               2.35                  61.32  5726.6  
12               4.77                  82.26  8299.2  
13               2.29                  58.72  3691.0  
14               3.08                  84.55  3020.6  
15               3.81                  69.34  5341.9  
16               2.45                  96.84  8063.6  
17               4.89                  56.88  8001.5  
18               4.85                  67.05  8426.8  
19               2.01                  55.67  4814.1  
20               2.99                  96.23  8604.4  
21               2.20                  93.87  9721.4  
22               2.14                  62.90  6382.7  
23               1.15                  83.00  8582.0  
24         

In [241]:
df['Performance_Score'].mean()

np.float64(2.8385)

In [3]:
df['Attendance_Percentage' ].max()

np.float64(96.84)

In [4]:
df['Salary'].sort_values(ascending = False)

31    99163
21    97214
0     94505
27    94044
7     93335
24    92623
20    86044
23    85820
18    84268
12    82992
5     82256
1     82251
16    80636
17    80015
29    79080
33    78925
26    73585
34    72941
28    72557
6     65222
22    63827
4     60535
11    57266
37    56105
32    55939
9     54538
15    53419
2     52662
25    52299
39    51976
35    51834
19    48141
36    48047
38    45707
8     40965
3     38392
10    38110
13    36910
30    32693
14    30206
Name: Salary, dtype: int64

In [11]:
df.rename(columns ={ 'Performance_Score': 'Rating'} )

Name  Age  Gender Department Joining_Date  Salary  Rating  \
0    Employee_1   50  Female    Finance   01-01-2015   94505    2.27   
1    Employee_2   36    Male  Marketing   26-03-2015   82251    1.44   
2    Employee_3   29  Female         HR   18-06-2015   52662    1.91   
3    Employee_4   42    Male  Marketing   10-09-2015   38392    2.71   
4    Employee_5   40  Female         HR   04-12-2015   60535    4.27   
5    Employee_6   44    Male    Finance   26-02-2016   82256    4.44   
6    Employee_7   32  Female         IT   20-05-2016   65222    1.03   
7    Employee_8   32    Male         HR   12-08-2016   93335    3.04   
8    Employee_9   45    Male  Marketing   05-11-2016   40965    2.67   
9   Employee_10   57  Female    Finance   28-01-2017   54538    1.89   
10  Employee_11   45    Male         HR   22-04-2017   38110    1.48   
11  Employee_12   24  Female  Marketing   15-07-2017   57266    2.35   
12  Employee_13   43  Female  Marketing   08-10-2017   82992    4.77   
13  Employee_14   23  Female  Marketing   31-12-2017   36910    2.29   
14  Employee_15   45  Female         HR   25-03-2018   30206    3.08   
15  Employee_16   51  Female         HR   17-06-2018   53419    3.81   
16  Employee_17   59  Female         HR   10-09-2018   80636    2.45   
17  Employee_18   23  Female         IT   03-12-2018   80015    4.89   
18  Employee_19   42  Female         HR   25-02-2019   84268    4.85   
19  Employee_20   54  Female         HR   20-05-2019   48141    2.01   
20  Employee_21   33  Female         HR   13-08-2019   86044    2.99   
21  Employee_22   43  Female         IT   05-11-2019   97214    2.20   
22  Employee_23   46    Male         HR   28-01-2020   63827    2.14   
23  Employee_24   48    Male  Marketing   21-04-2020   85820    1.15   
24  Employee_25   49  Female         HR   15-07-2020   92623    3.44   
25  Employee_26   37  Female  Marketing   07-10-2020   52299    3.01   
26  Employee_27   36  Female  Marketing   30-12-2020   73585    1.21   
27  Employee_28   24  Female  Marketing   24-03-2021   94044    2.11   
28  Employee_29   58  Female         IT   17-06-2021   72557    4.63   
29  Employee_30   28  Female         IT   09-09-2021   79080    1.96   
30  Employee_31   42  Female         IT   02-12-2021   32693    1.58   
31  Employee_32   30  Female         HR   24-02-2022   99163    2.96   
32  Employee_33   39    Male  Marketing   20-05-2022   55939    4.94   
33  Employee_34   25  Female         IT   12-08-2022   78925    1.97   
34  Employee_35   46    Male         IT   04-11-2022   72941    3.69   
35  Employee_36   35  Female         HR   27-01-2023   51834    4.05   
36  Employee_37   30  Female         IT   22-04-2023   48047    1.95   
37  Employee_38   47    Male         HR   15-07-2023   56105    3.91   
38  Employee_39   23  Female    Finance   07-10-2023   45707    2.47   
39  Employee_40   41    Male         IT   31-12-2023   51976    3.53   

    Attendance_Percentage  
0                   81.68  
1                   76.79  
2                   54.51  
3                   91.77  
4                   66.04  
5                   59.33  
6                   52.04  
7                   79.54  
8                   83.88  
9                   50.83  
10                  75.60  
11                  61.32  
12                  82.26  
13                  58.72  
14                  84.55  
15                  69.34  
16                  96.84  
17                  56.88  
18                  67.05  
19                  55.67  
20                  96.23  
21                  93.87  
22                  62.90  
23                  83.00  
24                  90.86  
25                  77.76  
26                  76.48  
27                  62.09  
28                  54.66  
29                  94.86  
30                  95.02  
31                  81.66  
32                  66.95  
33                  67.46  
34                  86.30  
35                  94.86  
36                  94

In [14]:
df

Name  Age  Gender Department Joining_Date  Salary  \
0    Employee_1   50  Female    Finance   01-01-2015   94505   
1    Employee_2   36    Male  Marketing   26-03-2015   82251   
2    Employee_3   29  Female         HR   18-06-2015   52662   
3    Employee_4   42    Male  Marketing   10-09-2015   38392   
4    Employee_5   40  Female         HR   04-12-2015   60535   
5    Employee_6   44    Male    Finance   26-02-2016   82256   
6    Employee_7   32  Female         IT   20-05-2016   65222   
7    Employee_8   32    Male         HR   12-08-2016   93335   
8    Employee_9   45    Male  Marketing   05-11-2016   40965   
9   Employee_10   57  Female    Finance   28-01-2017   54538   
10  Employee_11   45    Male         HR   22-04-2017   38110   
11  Employee_12   24  Female  Marketing   15-07-2017   57266   
12  Employee_13   43  Female  Marketing   08-10-2017   82992   
13  Employee_14   23  Female  Marketing   31-12-2017   36910   
14  Employee_15   45  Female         HR   25-03-2018   30206   
15  Employee_16   51  Female         HR   17-06-2018   53419   
16  Employee_17   59  Female         HR   10-09-2018   80636   
17  Employee_18   23  Female         IT   03-12-2018   80015   
18  Employee_19   42  Female         HR   25-02-2019   84268   
19  Employee_20   54  Female         HR   20-05-2019   48141   
20  Employee_21   33  Female         HR   13-08-2019   86044   
21  Employee_22   43  Female         IT   05-11-2019   97214   
22  Employee_23   46    Male         HR   28-01-2020   63827   
23  Employee_24   48    Male  Marketing   21-04-2020   85820   
24  Employee_25   49  Female         HR   15-07-2020   92623   
25  Employee_26   37  Female  Marketing   07-10-2020   52299   
26  Employee_27   36  Female  Marketing   30-12-2020   73585   
27  Employee_28   24  Female  Marketing   24-03-2021   94044   
28  Employee_29   58  Female         IT   17-06-2021   72557   
29  Employee_30   28  Female         IT   09-09-2021   79080   
30  Employee_31   42  Female         IT   02-12-2021   32693   
31  Employee_32   30  Female         HR   24-02-2022   99163   
32  Employee_33   39    Male  Marketing   20-05-2022   55939   
33  Employee_34   25  Female         IT   12-08-2022   78925   
34  Employee_35   46    Male         IT   04-11-2022   72941   
35  Employee_36   35  Female         HR   27-01-2023   51834   
36  Employee_37   30  Female         IT   22-04-2023   48047   
37  Employee_38   47    Male         HR   15-07-2023   56105   
38  Employee_39   23  Female    Finance   07-10-2023   45707   
39  Employee_40   41    Male         IT   31-12-2023   51976   

    Performance_Score  Attendance_Percentage   Bonus  
0                2.27                  81.68  9450.5  
1                1.44                  76.79  8225.1  
2                1.91                  54.51  5266.2  
3                2.71                  91.77  3839.2  
4                4.27                  66.04  6053.5  
5                4.44                  59.33  8225.6  
6                1.03                  52.04  6522.2  
7                3.04                  79.54  9333.5  
8                2.67                  83.88  4096.5  
9                1.89                  50.83  5453.8  
10               1.48                  75.60  3811.0  
11               2.35                  61.32  5726.6  
12               4.77                  82.26  8299.2  
13               2.29                  58.72  3691.0  
14               3.08                  84.55  3020.6  
15               3.81                  69.34  5341.9  
16               2.45                  96.84  8063.6  
17               4.89                  56.88  8001.5  
18               4.85                  67.05  8426.8  
19               2.01                  55.67  4814.1  
20               2.99                  96.23  8604.4  
21               2.20                  93.87  9721.4  
22               2.14                  62.90  6382.7  
23               1.15                  83.00  8582.0  
24         

In [17]:
dates =df['Joining_Date'] > '2021-01-01'

In [18]:
dates

0     False
1      True
2     False
3     False
4     False
5      True
6     False
7     False
8     False
9      True
10     True
11    False
12    False
13     True
14     True
15    False
16    False
17    False
18     True
19    False
20    False
21    False
22     True
23     True
24    False
25    False
26     True
27     True
28    False
29    False
30    False
31     True
32    False
33    False
34    False
35     True
36     True
37    False
38    False
39     True
Name: Joining_Date, dtype: bool

In [22]:
df.loc[df['Attendance_Percentage'].idxmax()]

Name                     Employee_17
Age                               59
Gender                        Female
Department                        HR
Joining_Date              10-09-2018
Salary                         80636
Performance_Score               2.45
Attendance_Percentage          96.84
Bonus                         8063.6
Name: 16, dtype: object

In [8]:
df['Joining_Date'] = pd.to_datetime(df['Joining_Date'], dayfirst=True)
df

Name  Age  Gender Department Joining_Date  Salary  \
0    Employee_1   50  Female    Finance   2015-01-01   94505   
1    Employee_2   36    Male  Marketing   2015-03-26   82251   
2    Employee_3   29  Female         HR   2015-06-18   52662   
3    Employee_4   42    Male  Marketing   2015-09-10   38392   
4    Employee_5   40  Female         HR   2015-12-04   60535   
5    Employee_6   44    Male    Finance   2016-02-26   82256   
6    Employee_7   32  Female         IT   2016-05-20   65222   
7    Employee_8   32    Male         HR   2016-08-12   93335   
8    Employee_9   45    Male  Marketing   2016-11-05   40965   
9   Employee_10   57  Female    Finance   2017-01-28   54538   
10  Employee_11   45    Male         HR   2017-04-22   38110   
11  Employee_12   24  Female  Marketing   2017-07-15   57266   
12  Employee_13   43  Female  Marketing   2017-10-08   82992   
13  Employee_14   23  Female  Marketing   2017-12-31   36910   
14  Employee_15   45  Female         HR   2018-03-25   30206   
15  Employee_16   51  Female         HR   2018-06-17   53419   
16  Employee_17   59  Female         HR   2018-09-10   80636   
17  Employee_18   23  Female         IT   2018-12-03   80015   
18  Employee_19   42  Female         HR   2019-02-25   84268   
19  Employee_20   54  Female         HR   2019-05-20   48141   
20  Employee_21   33  Female         HR   2019-08-13   86044   
21  Employee_22   43  Female         IT   2019-11-05   97214   
22  Employee_23   46    Male         HR   2020-01-28   63827   
23  Employee_24   48    Male  Marketing   2020-04-21   85820   
24  Employee_25   49  Female         HR   2020-07-15   92623   
25  Employee_26   37  Female  Marketing   2020-10-07   52299   
26  Employee_27   36  Female  Marketing   2020-12-30   73585   
27  Employee_28   24  Female  Marketing   2021-03-24   94044   
28  Employee_29   58  Female         IT   2021-06-17   72557   
29  Employee_30   28  Female         IT   2021-09-09   79080   
30  Employee_31   42  Female         IT   2021-12-02   32693   
31  Employee_32   30  Female         HR   2022-02-24   99163   
32  Employee_33   39    Male  Marketing   2022-05-20   55939   
33  Employee_34   25  Female         IT   2022-08-12   78925   
34  Employee_35   46    Male         IT   2022-11-04   72941   
35  Employee_36   35  Female         HR   2023-01-27   51834   
36  Employee_37   30  Female         IT   2023-04-22   48047   
37  Employee_38   47    Male         HR   2023-07-15   56105   
38  Employee_39   23  Female    Finance   2023-10-07   45707   
39  Employee_40   41    Male         IT   2023-12-31   51976   

    Performance_Score  Attendance_Percentage  
0                2.27                  81.68  
1                1.44                  76.79  
2                1.91                  54.51  
3                2.71                  91.77  
4                4.27                  66.04  
5                4.44                  59.33  
6                1.03                  52.04  
7                3.04                  79.54  
8                2.67                  83.88  
9                1.89                  50.83  
10               1.48                  75.60  
11               2.35                  61.32  
12               4.77                  82.26  
13               2.29                  58.72  
14               3.08                  84.55  
15               3.81                  69.34  
16               2.45                  96.84  
17               4.89                  56.88  
18               4.85                  67.05  
19               2.01                  55.67  
20               2.99                  96.23  
21               2.20                  93.87  
22               2.14                  62.90  
23               1.15                  83.00  
24               3.44                  90.86  
25               3.01                  77.76  
26               1.21                  76.48  
27               2.11                  62.09  
28               4.63  

In [9]:
df['Joining_Date'] = pd.to_datetime(df['Joining_Date'])
df['Joining_Year'] = df['Joining_Date'].dt.year

In [10]:
df['Joining_Year']

0     2015
1     2015
2     2015
3     2015
4     2015
5     2016
6     2016
7     2016
8     2016
9     2017
10    2017
11    2017
12    2017
13    2017
14    2018
15    2018
16    2018
17    2018
18    2019
19    2019
20    2019
21    2019
22    2020
23    2020
24    2020
25    2020
26    2020
27    2021
28    2021
29    2021
30    2021
31    2022
32    2022
33    2022
34    2022
35    2023
36    2023
37    2023
38    2023
39    2023
Name: Joining_Year, dtype: int32

In [40]:
df.loc[df['Attendance_Percentage'].idxmax()]

Name                             Employee_17
Age                                       59
Gender                                Female
Department                                HR
Joining_Date             2018-09-10 00:00:00
Salary                                 80636
Performance_Score                       2.45
Attendance_Percentage                  96.84
Bonus                                 8063.6
Joining_Year                            2018
Name: 16, dtype: object

In [46]:
df = df[df['Attendance_Percentage'] >= 60]

In [47]:
df

Name  Age  Gender Department Joining_Date  Salary  \
0    Employee_1   50  Female    Finance   2015-01-01   94505   
1    Employee_2   36    Male  Marketing   2015-03-26   82251   
3    Employee_4   42    Male  Marketing   2015-09-10   38392   
4    Employee_5   40  Female         HR   2015-12-04   60535   
7    Employee_8   32    Male         HR   2016-08-12   93335   
8    Employee_9   45    Male  Marketing   2016-11-05   40965   
10  Employee_11   45    Male         HR   2017-04-22   38110   
11  Employee_12   24  Female  Marketing   2017-07-15   57266   
12  Employee_13   43  Female  Marketing   2017-10-08   82992   
14  Employee_15   45  Female         HR   2018-03-25   30206   
15  Employee_16   51  Female         HR   2018-06-17   53419   
16  Employee_17   59  Female         HR   2018-09-10   80636   
18  Employee_19   42  Female         HR   2019-02-25   84268   
20  Employee_21   33  Female         HR   2019-08-13   86044   
21  Employee_22   43  Female         IT   2019-11-05   97214   
22  Employee_23   46    Male         HR   2020-01-28   63827   
23  Employee_24   48    Male  Marketing   2020-04-21   85820   
24  Employee_25   49  Female         HR   2020-07-15   92623   
25  Employee_26   37  Female  Marketing   2020-10-07   52299   
26  Employee_27   36  Female  Marketing   2020-12-30   73585   
27  Employee_28   24  Female  Marketing   2021-03-24   94044   
29  Employee_30   28  Female         IT   2021-09-09   79080   
30  Employee_31   42  Female         IT   2021-12-02   32693   
31  Employee_32   30  Female         HR   2022-02-24   99163   
32  Employee_33   39    Male  Marketing   2022-05-20   55939   
33  Employee_34   25  Female         IT   2022-08-12   78925   
34  Employee_35   46    Male         IT   2022-11-04   72941   
35  Employee_36   35  Female         HR   2023-01-27   51834   
36  Employee_37   30  Female         IT   2023-04-22   48047   
37  Employee_38   47    Male         HR   2023-07-15   56105   
38  Employee_39   23  Female    Finance   2023-10-07   45707   

    Performance_Score  Attendance_Percentage   Bonus  Joining_Year  
0                2.27                  81.68  9450.5          2015  
1                1.44                  76.79  8225.1          2015  
3                2.71                  91.77  3839.2          2015  
4                4.27                  66.04  6053.5          2015  
7                3.04                  79.54  9333.5          2016  
8                2.67                  83.88  4096.5          2016  
10               1.48                  75.60  3811.0          2017  
11               2.35                  61.32  5726.6          2017  
12               4.77                  82.26  8299.2          2017  
14               3.08                  84.55  3020.6          2018  
15               3.81                  69.34  5341.9          2018  
16               2.45                  96.84  8063.6          2018  
18               4.85                  67.05  8426.8          2019  
20               2.99                  96.23  8604.4          2019  
21               2.20                  93.87  9721.4          2019  
22               2.14                  62.90  6382.7          2020  
23               1.15                  83.00  8582.0          2020  
24               3.44                  90.86  9262.3          2020  
25               3.01                  77.76  5229.9          2020  
26               1.21                  76.48  7358.5          2020  
27               2.11                  62.09  9404.4          2021  
29               1.96                  94.86  7908.0          2021  
30               1.58                  95.02  3269.3          2021  
31               2.96                  81.66  9916.3          2022  
32               4.94                  66.95  5593.9          2022  
33               1.97                  67.46  7892.5          2022  
34               3.69                  86.30  7294.1          2022  
35               4.05         

In [54]:
df['Bonus'].fillna(0, inplace=True)


C:\Users\BASANT\AppData\Local\Temp\ipykernel_8316\1811041322.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Bonus'].fillna(0, inplace=True)
C:\Users\BASANT\AppData\Local\Temp\ipykernel_8316\1811041322.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Bonus'].fillna(0, inplace=True)


In [57]:
df[['Salary','Bonus']].corr()

Salary  Bonus
Salary     1.0    1.0
Bonus      1.0    1.0

In [62]:
df[df['Name'].str.startswith('A')]

Empty DataFrame
Columns: [Name, Age, Gender, Department, Joining_Date, Salary, Performance_Score, Attendance_Percentage, Bonus, Joining_Year]
Index: []

In [67]:
df['Department'].value_counts()

Department
HR           13
Marketing    10
IT            6
Finance       2
Name: count, dtype: int64

In [80]:
import pandas as pd
df.to_csv("reports.csv")