What is the use of numpy random array...

ranom is a funtion in python numpy module or libraray which is used to generate random number between a range and the occurance of numbers can be also defined .

In [3]:
import numpy as np 
import random 

In [20]:
x = np.random.randint(0, 10, size=10)  

In [21]:
x

array([4, 7, 7, 0, 9, 2, 3, 0, 4, 1], dtype=int32)

In [18]:
 y = np.random.rand(10)

In [19]:
y

array([0.95758582, 0.10372476, 0.31632635, 0.36109154, 0.86009059,
       0.04782105, 0.8914901 , 0.75499014, 0.27595958, 0.0426541 ])

Q whats the diferece bw randint() and rand()

randint() funtion is used to generate random number in numpy array

rand() funtion is used to generate random decimal values in numpy araay

In [28]:
s = np.random.shuffle(x)

In [31]:
s

In [27]:
x

array([0, 7, 4, 1, 0, 2, 4, 3, 9, 7], dtype=int32)

In [34]:
z = np.array([1,2,3,4,5,6,7,8,9])

In [35]:
z

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
np.random.shuffle(z)

In [40]:
z

array([3, 9, 2, 8, 6, 7, 1, 4, 5])

In [41]:
sh = np.random.permutation(z)

In [42]:
sh

array([5, 6, 4, 1, 8, 2, 7, 3, 9])

Q diffrence bw permutation and shuffle 


permutaion() fution is used to store the shuffled data in a new variable but shuffle() funtion does the changes in orignal array      

In [47]:
np.random.normal(0, 5, 10) 

array([ 7.83277178,  3.8829684 ,  5.35055821, -3.24401007,  0.48081278,
        0.73785294,  6.93116269,  2.53159327, -7.83379654,  4.90980523])

In [48]:
np.random.normal(5, 2, 10) 

array([1.6406644 , 6.91274522, 7.99669794, 4.46189107, 2.58323673,
       3.44066352, 4.37817749, 8.61344284, 7.40123073, 6.14918216])