create two matrices of shape 2 , 2 find the sum of these matrix 

In [9]:
import numpy as np 
array1 = np.array([1,2])
array2 = np.array([1,2])

In [103]:
sum_of_array = array1/ array2

In [104]:
sum_of_array

array([1., 1.])

Create 1d / 2d array function and araange funtion 

In [12]:
import numpy as np 

one_d = np.array([1,2,3,4,5])
two_d = np.array([0,9,8,7,6])

one_d_r = np.arange(10)
two_d_r = np.arange(10)

In [15]:
one_d


array([1, 2, 3, 4, 5])

In [16]:
two_d

array([0, 9, 8, 7, 6])

In [17]:
one_d_r

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
two_d_r

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

use the attributes of numpy in one  d array atleast use 5 attributes 

In [19]:
atr1 = one_d[1:5]

In [20]:
atr1

array([2, 3, 4, 5])

In [21]:
atr2 = one_d.T

In [22]:
atr2

array([1, 2, 3, 4, 5])

In [23]:
atr3 = one_d[0]

In [25]:
atr3

np.int64(1)

In [26]:
atr4 = one_d_r.reshape(2,5)

In [27]:
atr4

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [28]:
one_d.dtype

dtype('int64')

In [33]:
one_d.shape

(5,)

In [34]:
one_d.size

5

In [30]:
ones=np.ones(2)
ones

array([1., 1.])

In [31]:
zeros = np.zeros(58)

In [32]:
zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0.])

In [ ]:
create an array within a range of zero to 100 with step 3 


In [40]:
array_range = np.arange(1,100,3)

In [41]:
array_range

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49,
       52, 55, 58, 61, 64, 67, 70, 73, 76, 79, 82, 85, 88, 91, 94, 97])

In [ ]:
create an array of 3x3 and get first two rows 

In [43]:
three_m = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [44]:
three_m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [51]:
three_m_r2 = three_m[:2]

In [52]:
three_m_r2

array([[1, 2, 3],
       [4, 5, 6]])


create an one d array and reshape it 


In [54]:
xarray = np.arange(15)

In [55]:
xarray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [56]:
reshapedx = xarray.reshape(3,5)

In [57]:
reshapedx

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [59]:
reshapedx.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [84]:
reshapedx[0,2]

np.int64(2)

In [62]:
reshapedx[1,1]

np.int64(6)

In [63]:
reshapedx[2,0]

np.int64(10)

Create a one d array named unsorted array and sort it 

In [66]:
import numpy as np
unsorted_array = np.array([7,5,8,9,4,2,5,9,2,4,5])
unsorted_array

array([7, 5, 8, 9, 4, 2, 5, 9, 2, 4, 5])

In [67]:
sorted_array= unsorted_array.T

In [68]:
sorted_array

array([7, 5, 8, 9, 4, 2, 5, 9, 2, 4, 5])

create a 3x2 matrix named unsorted 2d array ad sort it by row wise and colunm wise 

In [72]:
unsorted_2d = np.array([[1,2],[8,9],[6,7]])

In [73]:
unsorted_2d

array([[1, 2],
       [8, 9],
       [6, 7]])

In [76]:
sorted_by_c = np.sort(unsorted_2d ,axis=1)

In [77]:
sorted_by_c

array([[1, 2],
       [8, 9],
       [6, 7]])

In [78]:
sorted_by_r = np.sort(unsorted_2d ,axis=0)

In [79]:
sorted_by_r

array([[1, 2],
       [6, 7],
       [8, 9]])

In [86]:
sales_data = np.array([
    [1, 150000, 180000, 220000, 250000],  # Paradise Biryani
    [2, 120000, 140000, 160000, 190000],  # Beijing Bites
    [3, 200000, 230000, 260000, 300000],  # Pizza Hub
    [4, 180000, 210000, 240000, 270000],  # Burger Point
    [5, 160000, 185000, 205000, 230000]   # Chai Point
])

print("==== Zomato sales analysis ==== ")
print("\n Sales data shape", sales_data.shape)
print("\n Sample data for 1st 3 restau: ", sales_data[:3])

==== Zomato sales analysis ==== 

 Sales data shape (5, 5)

 Sample data for 1st 3 restau:  [[     1 150000 180000 220000 250000]
 [     2 120000 140000 160000 190000]
 [     3 200000 230000 260000 300000]]


In [87]:
# total sales per year 

In [93]:
print(np.sum(sales_data , axis =0))

[     15  810000  945000 1085000 1240000]


In [105]:
yearly_total = np.sum(sales_data[:,1:],axis = 0)

In [106]:
yearly_total

array([ 810000,  945000, 1085000, 1240000])

In [100]:
# minimum sales per resturant 


In [113]:
min_sales = np.min(sales_data[:,1:],axis=1)

In [114]:
min_sales

array([150000, 120000, 200000, 180000, 160000])

In [115]:
# max sales per year 


In [117]:
max_sales = np.max(sales_data[:,1:],axis = 0)

In [118]:
max_sales

array([200000, 230000, 260000, 300000])

In [119]:
# Avg sales per year 

In [120]:
avg_sales = np.mean(sales_data[:,1:],axis = 0)

In [121]:
avg_sales

array([162000., 189000., 217000., 248000.])