In [ ]:
Numpy Questions

In [1]:
import numpy as np

In [4]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [5]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
sum_of_elements = np.sum(matrix)
sum_of_elements

np.int64(45)

In [9]:
sum_of_rows = np.sum(matrix , axis = 1)
sum_of_rows

array([ 6, 15, 24])

In [10]:
sum_of_columns= np.sum(matrix,axis =0)
sum_of_columns

array([12, 15, 18])

In [11]:
transpose_of_matrix = matrix.T

In [12]:
transpose_of_matrix

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [20]:
transpose_of_matrix_sorted = np.sort(transpose_of_matrix ) 

In [21]:
transpose_of_matrix_sorted

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [22]:
transpose_of_matrix_sorted_desc = np.flip(transpose_of_matrix_sorted) 
transpose_of_matrix_sorted_desc


array([[9, 6, 3],
       [8, 5, 2],
       [7, 4, 1]])