0D Arrays

In [1]:
import numpy as np

arr = np.array(42)

print(arr)

42


In [3]:
import numpy as np

oned = np.array([1, 2, 3, 4, 5])

print(oned)

[1 2 3 4 5]


In [4]:
import numpy as np

twod = np.array([[1, 2, 3], [4, 5, 6]])

print(twod)

[[1 2 3]
 [4 5 6]]


In [5]:
import numpy as np

threed = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(threed)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [6]:
print(arr.ndim)

0


In [7]:
print(oned.ndim)

1


In [8]:
print(twod.ndim)

2


In [9]:
print(threed.ndim)

3


In [10]:
import numpy as np

arr2 = np.array([1, 2, 3, 4], ndmin=5)

print(arr2)
print('number of dimensions :', arr2.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5
