Creating Array From existing data 

In [2]:
import numpy as np

array =np.array([1,2,3,4,5,6,7,8,9])
array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
arr1 = array[3:7]
arr1

array([4, 5, 6, 7])

 Stacking Array

In [8]:
arr1 = np.array([1,2,3])
arr2 = np.array([1,2,3])

varray = np.vstack((arr1,arr2))

In [9]:
varray

array([[1, 2, 3],
       [1, 2, 3]])

Using Range and Reshape

In [12]:
arrx = np.arange(1,11)
arrx

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
reshaped_arrx= arrx.reshape(2,5)

In [14]:
reshaped_arrx

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])