In [3]:
import numpy as np

matrix = np.loadtxt('3x3.csv', delimiter=',')

print(matrix)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [4]:
matrix[1,1]

np.float64(5.0)

In [ ]:
Converting Float Matrix to Int

In [5]:
int_matrix= matrix.astype(int)

In [6]:
int_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])