In [1]:
import numpy as np 
arr =np.array([1,2,3,4,5])
print (arr)

[1 2 3 4 5]


In [4]:
print("shape of arry",arr.shape)

shape of arry (5,)


In [5]:
arr2=np.array([[1,2,3,4,5],[1,2,3,4,5]])
print (arr2)

[[1 2 3 4 5]
 [1 2 3 4 5]]


In [7]:
print("shape",arr2.shape)

shape (2, 5)


In [8]:
arr2.size

10

In [9]:
arr.dtype

dtype('int64')

In [13]:
arr3= np.arange(12)
arr3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [14]:
reshaped_arr=arr3.reshape(3,4)
reshaped_arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [20]:
flat_arr=reshaped_arr.flatten()
flat_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
##ravel orignal view of the array instead of copy

In [21]:
flat_arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [22]:
reshaped_arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [24]:
reshaped_arr.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [26]:
arr3[2:10]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
arr3[2:10:2]

array([2, 4, 6, 8])

In [29]:
arr3[-9:-1]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
reshaped_arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [33]:
print("slicing in 2d array",reshaped_arr[1,1:3])

slicing in 2d array [5 6]


In [39]:
arr3[0]=40

In [40]:
arr3

array([40,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [38]:
arr3

array([40,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [50]:
two_darray= np.array([[1,2,3,4,5],[6,7,8,9,0],[1,2,7,6,8]])
two_darray

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0],
       [1, 2, 7, 6, 8]])

In [51]:
two_darray[1,1]

np.int64(7)

In [53]:
two_darray[:,1]

array([2, 7, 2])

In [54]:
unsorted_array=np.array([4,5,7,1,9,2,4,5,8,1])
unsorted_array

array([4, 5, 7, 1, 9, 2, 4, 5, 8, 1])

In [55]:
print(np.sort(unsorted_array))

[1 1 2 4 4 5 5 7 8 9]


In [56]:
unsorted_array= np.array([[1,8,3,9,5],[2,7,1,9,0],[1,2,5,6,1]])
unsorted_array

array([[1, 8, 3, 9, 5],
       [2, 7, 1, 9, 0],
       [1, 2, 5, 6, 1]])

In [58]:
np.sort(unsorted_array,axis=1)

array([[1, 3, 5, 8, 9],
       [0, 1, 2, 7, 9],
       [1, 1, 2, 5, 6]])

In [59]:
np.sort(unsorted_array,axis=0)

array([[1, 2, 1, 6, 0],
       [1, 7, 3, 9, 1],
       [2, 8, 5, 9, 5]])

In [63]:
a=np.arange(10)
b=np.arange(10,20)

In [65]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [66]:
b

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [67]:
np.concatenate((a, b))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [70]:
np.concatenate((a, b), axis=0)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
s